spring.application.name=din
spring.datasource.url=jdbc:postgresql://localhost:5432/din
spring.datasource.username=postgres
spring.datasource.password=lucas20


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
api.security.token.secret=${JWT_SECRET:my-secret-key}

##logging.level.org.springframework=DEBUG
##logging.level.org.hibernate=DEBUG
##logging.level.org.flywaydb=DEBUG
spring.flyway.schemas=public